# appveyor file for controller-msi

# General Build Configuration
version: "{build}"

os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

# Build Setup
build:
  verbosity: detailed


# Build Matrix
platform:
  - Win32

configuration:
  - Release


# Build Dependencies
install:
  - update.bat
  - dir


# Build Steps
build_script:
  - set PATH=C:\Program Files (x86)\WiX Toolset v3.11\bin;%PATH%
  - make.bat
  

# Post Build Steps
#after_build:
#  - msiexec /i Configurator.msi /quiet /qn /norestart /log install.log

# Package Artifacts
artifacts:
  - path: 'Configurator.msi'


# Build Artifact Push (tagged releases only)
deploy:
  # GitHub Releases
  - provider: GitHub
    auth_token:
      secure: h9x3AlXZv85ukTfop+9B6K0zjPek9FJWwwxGE+QvRklE87LQtq9Hh0YIiVf8ag++
    artifact: /.*\.msi/
    draft: true
    prerelease: false
    description: 'Windows installer for the Input Club Kiibohd Configurator'
